autoload/ddu/ui/ff.vim
close: https://github.com/Shougo/ddu-ui-ff/issues/14
=> fix: change capital case properly to make coexistence `previewVertical` and `previewFloating`

denops/@ddu-uis/ff.ts, doc/ddu-ui-ff.txt
=> Add an option to change the style of window border

autoload/ddu/ui/ff/filter.vim
=> Fix miscalculated layout

autoload/ddu/ui/ff.vim, denops/@ddu-ui-ff/preview.ts, denops/@ddu-uis/ff.ts, doc/ddu-ui-ff.txt
I will fix the import path and add doc if Shougo/ddu.vim#16 is marged.
=> Support getPreviewer()

denops/@ddu-ui-ff/preview.ts
Sorry, I forgot to reset `terminalBufnr`.
=> Reset terminalBufnr

autoload/ddu/ui/ff.vim, denops/@ddu-uis/ff.ts, doc/ddu-ui-ff.txt
I added autoAction parameter, which is the same as denite's one.
=> Add autoAction parameter

autoload/ddu/ui/ff.vim, denops/@ddu-uis/ff.ts, doc/ddu-ui-ff.txt
I wanted to customize the preview window border, but I couldn't find the appropriate parameters.
=> add previewFloatingBorder parameter

denops/@ddu-uis/ff.ts
Redrawn between item refresh and apply highlights. so use batch function to suppress this behavior.
=> Fix highlights flicker

autoload/ddu/ui/ff.vim
=> fix: Allow nested autocmd on autoAction

autoload/ddu/ui/ff.vim, denops/@ddu-uis/ff.ts, doc/ddu-ui-ff.txt
Auto preview is sometimes slow.
Add debounce option to delay triggering the auto action.
=> Add debounce for auto action

autoload/ddu/ui/ff/filter.vim
Fixed error `Undefined variable "id"`.
=> Fix undefined variable

autoload/ddu/ui/ff.vim, autoload/ddu/ui/ff/filter.vim, denops/@ddu-uis/ff.ts, doc/ddu-ui-ff.txt
Add floating title option for ddu float window, filter window and preview window.
=> Add floating title

denops/@ddu-ui-ff/preview.ts
=> Escape preview buffer name

doc/ddu-ui-ff.txt
update doc for this issue 
https://github.com/Shougo/ddu-ui-ff/issues/88
=> update doc for cursor mark

denops/@ddu-uis/ff/preview.ts
Do not set filetype or highlights when content loading fails.
Previously, if the content loading failed and the item has a highlight, an error would occur trying to highlighting to the invalid position.
=> Fallback when content loading fails

denops/@ddu-uis/ff.ts, denops/@ddu-uis/ff/preview.ts, doc/ddu-ui-ff.txt
Users can easily set up dynamic window position calculations.
=> Evaluate window or preview window position parameters

autoload/ddu/ui/ff.vim, autoload/ddu/ui/ff/filter.vim, denops/@ddu-uis/ff.ts
The title for floating window is added in 0.9.0
=> Support nvim-0.9.0 earlier

doc/ddu-ui-ff.txt
SSIA
Blocked by https://github.com/Shougo/ddu.vim/pull/83
=> docs: Refine faq about applying specific syntax

denops/@ddu-uis/ff.ts
`#closeBuffer()` is called recursively.
In Vim and using `floating`,
1. `#closeBuffer()` is called.
2. `#closeFilterWindow()` is called in `#closeBuffer()`
3. `:close` command is called in filter window.
4. `WinClosed` autocmd raised and `ddu#ui#do_action('quit')` is called.
5. `#closeBuffer()` is called again before the first call finishes.
(Maybe) Nothing.
But it will cause bugs.
There are many differences, but the reason is indentation.
```diff
> git diff -b
diff --git a/denops/@ddu-uis/ff.ts b/denops/@ddu-uis/ff.ts
index b363689..197d257 100644
--- a/denops/@ddu-uis/ff.ts
+++ b/denops/@ddu-uis/ff.ts
@@ -175,6 +175,7 @@ export class Ui extends BaseUi<Params> {
#restcmd = "";
#prevWinInfo: WinInfo | null = null;
#filterBufnr = -1;
+  #bufferClosing = false;
override async onInit(args: { …
```
=> fix: prevent multiple calls to #closeBuffer

autoload/ddu/ui/ff.vim
=> fix: prop_type_add only bufnr

denops/@ddu-uis/ff.ts
=> fix: remove debug log

doc/ddu-ui-ff.txt
=> fix: doc `ddu#ui#ff#restore_cmaps()`

autoload/ddu/ui/ff.vim
It differs from the description in the documentation.
=> fix: `filterUpdateMax` condition

denops/@ddu-uis/ff.ts
=> Fix tabpage left at using `tab` split and after UI closed

denops/@ddu-uis/ff.ts, doc/ddu-ui-ff.txt
=> Add updateSelectedItems()
