autoload/ddu/ui/std.vim
The last argument of ddu#ui#std#_highlight() must be the length
=> Fix argment of ddu#ui#std#_highlight()

denops/@ddu-uis/std.ts
Added a setting to not show `signcolumn` in` ddu-ui-std`, since it is also shown in `ddu-ui-std` if it is set to show` signcolumn`.
=> Add signcolumn hide option

denops/@ddu-uis/ff.ts
* Set `buftype=nofile` for the UI buffer
* Fix `chooseAction` can somehow make two `ddu-ff-default` buffers
=> Fix buffer manipulation

denops/@ddu-uis/ff.ts
Buffer initialization is incomplete when the FF buffer is reopened.
Also, the behavior changes depending on the global option `&hidden`.
1. Do `:set nohidden`.
2. Open the FF buffer. (`FileType` event is fired.)
3. Close the FF buffer. (The buffer becomes unload and syntax etc. are lost.)
4. Re-open the FF buffer. (`FileType` event is **NOT** fired.)
Initialize the buffer options if `winid < 0` (it is not assigned to window).
Always unload the ff buffer on quit.
=> Fix initialization of the ff buffer

autoload/ddu/ui/ff/filter.vim
This PR is fix can't open filter window with `E691: Can only compare List with List"` when using under setting.
```vim
call ddu#custom#patch_global({
\   'ui': 'ff',
\   'uiParams': {
\     'ff': {
\       'split': 'floating',
\       'floatingBorder': ['.', '.', '.', ':', ':', '.', ':', ':'],
\     },
\   },
\ })
```
=> Fix can't open floating filter window when floatingBorder is List

denops/@ddu-uis/ff.ts
- fix problem that may cause `E25` error.
- fix problem that filter windows does not open when execute `chooseAction`.
After executing `chooseAction` with filter window displayed, an error occurs when trying to open filter window. Also, if `startFilter` is `true`, I think the filter window should remain visible after the `chooseAction` is executed.
```vim
:call ddu#start({})
<ESC><C-w>p
:call ddu#ui#ff#do_action('chooseAction')
:call ddu#ui#ff#do_action('openFilterWindow')
```
<details>
<summary>minimal.vim</summary>
```vim
let plugins = [
\ "/home/erw7/.config/nvim/dein/repos/github.com/Shougo/ddu-ui-ff",
\ "/home/erw7/.config/nvim/dein/repos/github.com/vim-denops/denops.vim",
\ "/home/erw7/.config/nvim/dein/repos/github.com/Shougo/ddu.vim",
\ …
```
=> fix problems with filter window

autoload/ddu/ui/ff/filter.vim
filterでのバックスペースの挙動を制限することを提案します。
現在、`backspace`に`eol`をセットしている場合バックスペースによって改行が削除され、前回filterに入力した内容が表示されます。  
これはバッファとしては当たり前のことですが、「フィルター」としては違和感のある挙動だと感じました。
私はfilterを利用している時、それが通常のバッファであると認識はせず、特殊な「検索窓」のようなものに入力をしていると認識します。  
そのため、バックスペースによって改行が削除されたとき、前回の入力内容が唐突に出てきたように感じます。
この提案は各自で対応可能なものですが、ファジーファインダーとしてプラグイン側で対応した方がわかりやすいのではないか、と思いました。
よろしくお願いします。
(行頭行末での左右矢印キーで前後の行に移動するのも制限した方が良いと思うのですが、方法がわからない、かつ、問題となる頻度が小さいと感じたので含めていません)
=> don't allow backspacing over line breaks in filter

autoload/ddu/ui/ff.vim
In the current implementation, `previeeFloatingBorder` is applied only when `previewVertical` is `v:false`.
But I think the border should be specifiable when `previewVertial` is `v:true` too.
=> Make specifiable border when `previewVertical = v:true` too

denops/@ddu-uis/ff.ts
`cursorPos` of uiParams is set `-1`. But in doc, `0`.  
When `cursorPos` is -1, the following bug occurs. The cursor moves to an unexpected position. So I think 0 is correct.
https://user-images.githubusercontent.com/61523777/187329681-d5ad539a-fea9-4b68-b688-f1ca0269b441.mov
Also, I fixed the syntax error: Line 441.  The `async` method must return `Promis<T>`.
=> Fix cursorPos default value

autoload/ddu/ui/ff.vim
I used `previewFloating` feature, and I encountered unexpected behavior.
So I fixed that.
https://user-images.githubusercontent.com/19731661/198838827-4d2a6f8b-8ec6-4159-b342-9e6e25a5fca1.mov
https://user-images.githubusercontent.com/19731661/198838898-c09b7d26-2b26-4dd9-81f1-184d1de7b7b3.mov
=> Fix previewFloating changes other window size

denops/@ddu-ui-ff/preview.ts
I want to apply `floating` of `ddu-ui-ff-param-highlights` to preview window. I changed to that in this PR.
=> Apply floating highlight also preview window

autoload/ddu/ui/ff.vim
As a result of #64, if we use `preview` action with `autoAction`, cursor will move to preview window.
Make not to trigger `autoAction` if autocmd is in doing action.
=> fix Check in_action in autoAction

denops/@ddu-uis/ff.ts
If ui-ff is started during `input()` for example, the command line is wrongly restored after closing the ui-ff.
At the moment there is no need to restore other command line types, so restore only `:` type command line.
=> Do not restore cmdline if its type is not `:`

denops/@ddu-uis/ff.ts
ddu.vim can now get an action even if the item is empty in commit https://github.com/Shougo/ddu.vim/commit/e2114fd24d5a9ab1e01cc9ef9e481bb3ec19f3b4.
So `chooseAction` can now be performed even if the item is empty.
=> Allow chooseAction to be executed even when the items are empty.

autoload/ddu/ui/ff/filter.vim, denops/@ddu-uis/ff.ts, doc/ddu-ui-ff.txt
Why not 😃 
The default value `FloatBorder` is chosen as the same as `nvim_open_win`.
The PR includes a small refactoring as well:
- Avoid multiple calls of `fn.bufwinnr`
- Removes a duplicated code to set the highlight of the filter.
Hope you like the changes.
=> Add an option to choose the highlight of the border of floating windows

autoload/ddu/ui/ff.vim, denops/@ddu-uis/ff.ts, doc/ddu-ui-ff.txt
The screen flickers when using auto preview. This is because preview action is executed asynchronously.
Add `sync` option.
=> Add sync option to AutoAction parameter

denops/@ddu-ui-ff/preview.ts
I changed buflisted → bufexists for unlisted buffer (like each plugin based buffer) to be previewed.
=> chage buflisted to bufexists

autoload/ddu/ui/ff.vim
Fix the following error:
```
[denops] Failed to handle message 2,invoke,dispatch,ddu,uiAction,file_rec,cursorNext,[object Object] 0,function ddu#ui#ff#_cursor[10]..ddu#ui#ff#_do_auto_action, line 2: Vim(let):E716: Key not present in Dictionary: "delay, { -> s:do_auto_action() })"
```
This error is caused when I don't set autoAction. 
Because `s:auto_action` will set be `{}` by `ddu#ui#ff#_reset_auto_action()`, so the `delay` key will be undefined.
=> Fix do_auto_action

autoload/ddu/ui/ff.vim
preview window was not shown if given an array to `previewFloatingBorder`. (e.g. `[".", ".", ".", ":", ":", ".", ":", ":"]`)
Use `isnot#` instead of `!=#` for avoid `E691`.
See also: https://github.com/Shougo/ddu-ui-filer/pull/30
=> Fix preview fails if given an array to `previewFloatingBorder`

denops/@ddu-ui-ff/preview.ts, denops/@ddu-uis/ff.ts, doc/ddu-ui-ff.txt
I would like to change the CusorLine highlight in ddu-ui-ff to make the selected choice stand out.
I have added `highlights.floatingCursorLine` to the ddu-ui-ff options. This is a Neovim-only option.
=> Add new option to change "CursorLine" highlight of floating window for Neovim

denops/@ddu-ui-ff/preview.ts, denops/@ddu-uis/ff.ts, doc/ddu-ui-ff.txt
I want to add "previewExecute" action, it provides preview window operation to user.
I mainly intend to scrolling preview window.
```vim
nnoremap <buffer> <nowait> d <Cmd>call ddu#ui#do_action('previewExecute', #{command: "normal! \<C-d>"})<CR>
nnoremap <buffer> <nowait> u <Cmd>call ddu#ui#do_action('previewExecute', #{command: "normal! \<C-u>"})<CR>
```
=> [Feature Request] Add `previewExecute` action

autoload/ddu/ui/ff.vim
In Vim9, `'cursorline'`  highlight always overrides highlights added by ddu-ui-ff.
It should behive same as Neovim not to override.
Set the `override` flag to `prop_type_add()`.
This flag has been added in patch [`9.0.0144`](https://github.com/vim/vim/commit/f4ba8bc47eb3c6b5899ef31d083b9b8f0d4ca456).
=> fix: Make highlight override cursorline in Vim9

autoload/ddu/ui/ff.vim
SSIA
See also the `posinvert` option in `:help popup_create-arguments`.
=> fix Avoid unexpected pos use if previewFloating is enabled in Vim9

autoload/ddu/ui/ff.vim, denops/@ddu-uis/ff.ts, denops/@ddu-uis/ff/preview.ts
SSIA
Before this PR, you have seen following window layout when doing below steps:
- Set `uiParams.split` to `horizontal`
- Set `uiParams.previewSplit` to `vertical`
- call `openFilterWindow` action after `preview` or `togglePreview` action:
```
┌───────────────┬─────────────┐
│ ddu-ff-filter │             │
├───────────────┤             │
│               │             │
│               │   preview   │
│     ddu-ff    │             │
│               │             │
│               │             │
└───────────────┴─────────────┘
```
After this PR:
```
┌─────────────────────────────┐
│        ddu-ff-filter        │
├───────────────┬─────────────┤
│               │             │
│               │             │
│     ddu-ff    │   preview   │
│               │             │
│               │ …
```
=> fix: Open filter window always in top

denops/@ddu-uis/ff/preview.ts
In Vim9 if `uiParams.previewFloating` is enabled, an empty window stays behind on quit.
Use `bufwinnr()` instead of `winbufnr()` to check buffers to wipe out.
=> fix: Use bufwinnr() instead of winbufnr()

denops/@ddu-uis/ff.ts, denops/@ddu-uis/ff/preview.ts
before this PR, `ddu#ui#winids({name})` return bellow
-  dduWindow
-  filterWindow ( if possible )
after this PR, return bellow
- dduWindow
-  filterWindow ( if possible )
- previewWindow ( if visible )
NOTE:
to get previewWinId, I add getter to `PreviewUi` class.
but there are other better method to get previewWinId.
=> winIds contains previewWinId

denops/@ddu-uis/ff.ts
In Vim and using `floating`.
After the popup closes, the next window after the filter window will be focused.
Move focus to the window that had focus before ddu started.
=> fix: focus last window after close popup in Vim

autoload/ddu/ui/ff.vim
If we make the following settings.
The highlight column position is not valid.
- Specify multibyte characters (byte length != display width) in the source name alias.
- Enable source name display.
Column position of the highlight is calculated by byte length.
However, `strwidth()` is used.
Use `strlen()` instead.
=> fix: use byte length instead character length for the item prefix

autoload/ddu/ui/ff/filter.vim
Re-creates the filter buffer if the user accidentally deletes it.
=> fix: re-create filter buffer if not exists

denops/@ddu-uis/ff.ts, denops/@ddu-uis/ff/preview.ts
Prevent statusline breaks due to unexpected `%`.
And some refactor.
=> Escape statusline format

autoload/ddu/ui/ff.vim
This PR suppresses "No matching autocommands" message on opening/closing filter window like this.
```
No matching autocommands: User Ddu:ui:ff:openFilterWindow
No matching autocommands: User Ddu:ui:ff:closeFilterWindow
```
1. `vimrc.vim`
```vim
set nocompatible
set runtimepath^=~/.cache/vim/pack/minpac/opt/denops.vim
set runtimepath^=~/.cache/vim/pack/minpac/opt/ddu.vim
set runtimepath^=~/.cache/vim/pack/minpac/opt/ddu-ui-ff
call ddu#custom#patch_global(#{ ui: 'ff' })
autocmd FileType ddu-ff nnoremap i <Cmd>call ddu#ui#do_action('openFilterWindow')<CR>
autocmd FileType ddu-ff nnoremap q <Cmd>call ddu#ui#do_action('quit')<CR>
nnoremap @ <Cmd>call ddu#start()<CR>
```
2. Open Vim with `vim -u /path/to/vimrc.vim`
3. Type `@` to start ddu.
4. Type `i<CR>` to open and close filter window.
5. …
=> Fix "No matching autocommands" error
